apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi-pvc
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi