apiVersion: v1
kind: Service
metadata:  
  name: rabbitmq-svc
  namespace: rabbitmq
spec:
  selector:    
    app: rabbitmq
  type: ClusterIP
  ports:  
  - name: rabbitmq
    port: 5672
    targetPort: 5672
    protocol: TCP