apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        hostname: rabbit
        image: rabbitmq:3
        ports:
        - containerPort: 5672
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
