apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin
  namespace: powerdns
  labels:
    app: powerdns-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-admin
  template:
    metadata:
      labels:
        app: powerdns-admin
    spec:
      containers:
      - name: powerdns-admin
        image: pschiffe/pdns-admin
        ports:
        - containerPort: 8080
        env:
        # Mysql settings
        - name: PDNS_ADMIN_SQLA_DB_HOST
          value: "'mysqlcluster.mysql-cluster.svc.cluster.local'"
        - name: PDNS_ADMIN_SQLA_DB_PORT
          value: "'3306'"
        - name: PDNS_ADMIN_SQLA_DB_USER
          value: "'pdns'"
        - name: PDNS_ADMIN_SQLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pdns-db-admin-user-pass
              key: password
        - name: PDNS_ADMIN_SQLA_DB_NAME
          value: "'pdns'"
        - name: PDNS_API_URL
          value: "http://powerdns-mysql:8081/"
        - name: PDNS_API_KEY
          value: "abc123"
        - name: PDNS_VERSION
          value: "4.7.2"
      volumes:
      - name: powerdns-admin-data
        persistentVolumeClaim:
          claimName: powerdns-admin-pvc