apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pvc
  namespace: uptime
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi