apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc
  namespace: media
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi