apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        ports:
        - containerPort: 7878
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "44" # Video group
        - name: UMASK
          value: "002"
        - name: TZ
          value: "Australia/Brisbane"
        volumeMounts:
        - mountPath: "/config"
          name: radarr-config
        - mountPath: "/mnt/media"
          name: media-nfs
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-pvc
        - name: media-nfs
          persistentVolumeClaim:
            claimName: media-nfs-pvc
