apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bookstack-secrets
  namespace: md-converter-dev
spec:
  encryptedData:
    bookstack_token: AgC8dlr7cfoAE1ejNmKE5Id+SidTpeIaF34aQBLQaHgbZU5pnI/rzWTKwdiCCHjpMwKIUq4K74yHwu/SNY9b++msavNSBmlBfRDAK9EBM+ueoxKowckFsotiSdsMq9A0wyxkeybQpdLtQ2HMWrvKcIiVBBUWSmVWPyZfWewX/lQOslAEqFS4OlWTGK6n3GYnrh8lAmtWD5rWRa6Qx8mSk0QpiJE2RA6sK11iCedRpmLwUi4pQbX0bfBbSVARlSpSPX/852lrnQddnUVU+fANN+0dybUBDh5v7fVh2Ng4iFvvu0AKW9K6VK9XnTy1iulFmtdNBrpHhFlc8Sq+2xPSMAduIXIHhTZQGC4XkE/AdfhQ8uV9+QMCQTscnPggKmIDigWLEeYnNPQkiDBzucaz73d2XYpE5bhbMNb9bPsQRsXH1WpNoygGLPQ0+nyVdIidRQl/vpj+6qruiy8U49dlfbdzpXxHF5cdvPhCFBT5xCq46fasb44imy9uZzL3jyt/AkPQTeRwVwfDnhn7ZPWbixGph/ad/KzPWECJiEEX71auRUAysvDzYnqSaVjahB6o5pqev++bkDeXk9VyvxXMW+lqGvadHJ+qm0JP4LKjT1owSxjJCVwB4lHvL61bbxhBKgj+e0cLa3WMrC6M6c3EIPBzSlOwQp6iW9E8TLD+kJTu8djsDJg5UX+sBrQhaW0tLWM+GxbQaoARwLTQxrlznmbNRFxAaHuYgV5EOpG80rQJGGijVr7JHnLbJWmfFnJDDXtzXGubxtg8DwW9jnseYtBZuQ==
    bookstack_url: AgCxx7ru2wKUgCc50iB7fo5vRsyrqGAbwgZa4egZGwHzlYhxUP0dxZ6JD3LCBUKuyfKUWZJ0nxppr/yW2NSrbjMzb1XkLGrrnDkypYMt9fV+HxJMmTtsbBbSsl4J0ergAvuBKmQoTLcOuutAOKtHurrjaVD3hh8iaSQHZ2S/v+wnief8R7875KIIQiRzT3iofW/VsSnmBj7peEUWDROsdXbKbRhczaYMg1MVVPlhu5TirQjbnGkweov/q/OZQcWND5XRR8/nNHwPesKA4vSNU+5Vj7VBn751C8+X1gjH5XSuxkxat8SYTjFz16ZqhEA8Z4nU9f7oEGAB3XawTYP30cSyGQ2nAjQ77gN8Bf8gY17Lmi01zc7aPyOi6Vvg87TGSyNlOgUgV8W++0fTE3jM/N2TmVb1QEv4dhPvW9OFXyQFJnnGNQXvz77LGhaH4TszcgQhDWfJOXRo4bAGHqekE1BbCt7lfdPL9Y69mKlDN3oonC0wHHb+130tfzGmIVx1GfL29rIQt/pNLSYHtbdQk0QHak2W6ewwRhflxMQOBB9S6cHB2bqM8ShD1S8CpbEV9slf2sTDMgf/l4aikWguyAzZlh1+w/l1vzGX6UWPqg9SelbVzTkq98qFBsWY+09Cyp2sDQQinI8NYgwdB5Z7zORmz0Ah0WoW0QkoZML2E/OksXJKOG+IguaY6+FgFYtj8HEGWJzAm+++laGVtgcT9jL1wph3+aLVfnnN2IF03KM=
  template:
    metadata:
      creationTimestamp: null
      name: bookstack-secrets
      namespace: md-converter-dev
    type: Opaque
status: {}

