apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
      - name: worker
        image: ghcr.io/alex-j-butler/markdown-converter-api/worker:851babc
        env:
        - name: FLASK_BROKER_URL
          value: "amqp://guest@rabbitmq-svc.rabbitmq.svc.cluster.local"
        - name: FLASK_RESULT_BACKEND_URL
          value: "celery_amqp_backend.AMQPBackend://guest@rabbitmq-svc.rabbitmq.svc.cluster.local"
        - name: FLASK_QUEUE_NAME
          value: "dev"
        - name: FLASK_S3_REGION_NAME
          value: "ap-southeast-2"
        - name: FLASK_S3_ENDPOINT_URL
          value: "https://s3.ap-southeast-2.amazonaws.com"
        - name: FLASK_S3_BUCKET_NAME
          value: "ajb-convert"
        - name: FLASK_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: access-key
        - name: FLASK_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secrets
              key: secret-key
        - name: FLASK_BOOKSTACK_URL
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: bookstack_url
        - name: FLASK_BOOKSTACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: bookstack_token
