apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBnB/ppdKo64tUhg3QjiODuQFlknbhdx7r1fWnMzBnFOPeOdzAmqpqwmj/cOQIUgXDNNW1lWMOwZK0CLvwLso/fiVzk4E2sYLlTC/tTK/Wvl2SvkWYXuXXcL673i5OVOTx3/isz0ZeannL2zF03IaMo2UQ+9FC7CG/Bk1Il+p4Cj2po6JAc4gVlO6i3G/5z+JEqsF6Ce6T/dDLuNHip0GN0071aI3I9MW2pvBZQ22ce7byA7ccQswZ74EQvLjUjBI3r5bOG+1BbMZ1Zxa74ow9lSEfUSgFOGm0EWM2VVVe28v9t8TrGQuXX7PmeVxwUxpCP1BsPM2AC0++dparzcoOFUhSk6CI9MS8UBcX/yzf5UT41BtUxRhqZ09gOIiYhv1tXsiyrllsBd4h8/QQ+75NpSROH72NhcIeL/rREP1jWugXsJUVyOXIV9yXXhd3s9FK5MBYfEUnwo172wD4Uwq71HOshyKmXyMYengp56D4+a09hMETjpEevOjECLObkkEmHdlfAjnjSz7M1rZ1R3eYhNbvnE+KHuCHgzI/P8wHG5XAeBioJp1x4mZUNB50lNXuB6RKVqo5UE28S0Gkna+purvpta4PQyWC6Mwt5R2H3DyBmfnUXybvHfIfDA15hbxxwXJqz5ttyFs/uKB8KlG/I0zcb1X9CphPDafzyfjMWoJXZMjdRjG/X00TqwbCdgQJNXPFwvjdVZOZJuk8j/QqWlUM9Ur4kthcMB7Ke0DQyzk2/xm2Nykdl
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
status: {}

