apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksmd
  labels:
    app: tasksmd
spec:
  selector:
    matchLabels:
      app: tasksmd
  template:
    metadata:
      labels:
        app: tasksmd
    spec:
      containers:
      - name: tasksmd
        image: baldissaramatheus/tasks.md
        ports:
        - containerPort: 8080
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
