apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: snipe-it-app-key
  namespace: snipeit
spec:
  encryptedData:
    app-key: AgBLMblHUJ7mhRItp8cujDTMTd9l2BRLI4YDNht8G8qg1yO4TfcenMR70eDTEvT5AzwtdLwxXqnNR0WJ3hfOxGuaTC3OrrAJ31YoSTCJe0HhOB/2mvtS/tmRqKBys/O7Qb/gfazQm2JgdoTK3HcaZRLBRAIH7gpr07FK1cnWALyzZ8DbPMwwvzehQLocqkV/UAdRbZiHCRPRz4FchSJQcczTeRdUzT3hhiYeqKvFHpJSIpyYVqE41trVlyoPUg+XWecT2wYPYxbYZt/P75MWmLzSFyV/3RXcYx97q7CdclRFrWBGupdyMzAH7Q5QNzTYZcEij3lWp2DkbFRftohZpfItmiZ56mYkZXhQOGrRG7YYTX5N4obDNzfDdJME8Pn9RQDaJuvidGpvdPLqinQMJGEvfvNFpgukUBkKyaGOSKN9BBpT4gy2vL8muFt531vTFwpc0fpF2JlER9luvvPMYqk6kR/eNgzbWElv69c98/S1moAvwkQwiKtqaHAESNKe1DYF6fGo19r8XKIW1/WOX4bD5s7ecTZ22NqwwF5ayBNA4XU0fDFDgdMmPbszwbSCFUxVhOL5Hd+352cZnF/Cmgmgy2/zc8/HGberTbVbUuyyPEBXWwMayOq39ckjvUlmLBsbPPrs2BtzFEuByQaaIAqHtzw7YWksgkwp5gprcnDf1ZIYsGZ4jUIj6D0CyRTKRr4oM3mUhlSvx0NmaRdufITD6cZKcn+5igCtTlfiPlDI4SLaBGQQ96NyEMyjx+caN+CDD5s=
  template:
    metadata:
      creationTimestamp: null
      name: snipe-it-app-key
      namespace: snipeit
    type: Opaque
status: {}

