ingress-nginx:
  controller:
    electionID: "internal-ingress-controller-leader"
    ingressClassResource:
      name: internal-nginx  # default: nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx