apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: media
  name: media-nfs
  labels:
    storage.k8s.io/name: media-nfs
    storage.k8s.io/created-by: alex-j-butler
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: media
    name: media-nfs-pvc
  nfs:
    server: 10.0.3.64
    path: /volume1/Media
    readOnly: no