kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: media
  name: media-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi