apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: auth
  labels:
    app: keycloak
spec:
  instances: 1
  ingress:
    enabled: true
    className: nginx
  additionalOptions:
    - name: "db-url-database"
      value: "jdbc:mysql://mysqlcluster.mysql-cluster.svc.cluster.local/keycloak"
  db:
    driver: mysql
    host: "mysqlcluster.mysql-cluster.svc.cluster.local"
    usernameSecret:
      name: keycloak-secrets
      key: db_username
    passwordSecret:
      name: keycloak-secrets
      key: db_password
  http:
    tlsSecret: keycloak-tls
  hostname:
    hostname: auth.alex-j-butler.com
