apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
  labels:
    app: bookstack
spec:
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: bookstack
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      initContainers:
      - name: init-bookstack-volume
        image: busybox:1.36
        env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: app-key
                key: key
        command: ['sh', '-c', "echo $APP_KEY > /config/BOOKSTACK_APP_KEY.txt; sleep 2"]
        volumeMounts:
        - mountPath: "/config"
          name: bookstack-temp
      containers:
      - name: bookstack
        image: linuxserver/bookstack:version-v23.06
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "986"

        ### Database configuration
        - name: DB_HOST
          value: "mysqlcluster.mysql-cluster.svc.cluster.local"
        # Database user
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-db-user-pass
              key: username
        # Database password
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-db-user-pass
              key: password
        # Database db name
        - name: DB_DATABASE
          value: "bookstack"

        ### Application configuration
        - name: APP_URL
          value: "https://docs.alex-j-butler.com"
        - name: APP_PROXIES
          value: "*"
        - name: APP_DEBUG
          value: "false"
        - name: FILE_UPLOAD_SIZE_LIMIT
          value: "100"
        - name: "SESSION_LIFETIME"
          value: "600"

        ### Session and Cache driver
        - name: CACHE_DRIVER
          value: "database"
        - name: SESSION_DRIVER
          value: "database"

        ### S3 Storage configuration
        - name: STORAGE_TYPE
          value: "local"
        volumeMounts:
        - mountPath: "/config"
          name: bookstack-temp
        - mountPath: "/config/www/images"
          name: images
        - mountPath: "/config/www/files"
          name: files
        - mountPath: "/config/www/uploads"
          name: attachments
        #readinessProbe:
        # httpGet:
        #   path: /status
        #   port: 80
        # initialDelaySeconds: 5
        # timeoutSeconds: 1
        # periodSeconds: 15
        # livenessProbe:
        #  httpGet:
        #    path: /login
        #    port: 80
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 1
        #  periodSeconds: 15
      volumes:
        - name: bookstack-temp
          emptyDir:
            sizeLimit: 500Mi
        - name: images
          persistentVolumeClaim:
            claimName: uploads-nfs-pvc
        - name: files
          persistentVolumeClaim:
            claimName: fileuploads-nfs-pvc
        - name: attachments
          persistentVolumeClaim:
            claimName: attachments-nfs-pvc
