apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
  labels:
    app: bookstack
spec:
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: bookstack
      imagePullSecrets:
        - name: githubregcreds
      initContainers:
      - name: init-bookstack-volume
        image: busybox:1.36
        env:
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: app-key
                key: key
        command: ['sh', '-c', "echo $APP_KEY > /config/BOOKSTACK_APP_KEY.txt; sleep 2"]
        volumeMounts:
        - mountPath: "/config"
          name: bookstack-temp
      containers:
      - name: bookstack
        #image: linuxserver/bookstack
        image: ghcr.io/alex-j-butler/docker-bookstack/bookstack:v23.02.2
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "986"

        ### Database configuration
        - name: DB_HOST
          value: "mysqlcluster.mysql-cluster.svc.cluster.local"
          #value: "10.102.92.84"
        # Database user
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-db-user-pass
              key: username
        # Database password
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bookstack-db-user-pass
              key: password
        # Database db name
        - name: DB_DATABASE
          value: "bookstack"

        ### Application configuration
        - name: APP_URL
          value: "https://docs.int.alex-j-butler.com"
        - name: APP_DEBUG
          value: "true"
        - name: FILE_UPLOAD_SIZE_LIMIT
          value: "100"
        - name: "SESSION_LIFETIME"
          value: "600"

        ### Session and Cache driver
        - name: CACHE_DRIVER
          value: "redis"
        - name: SESSION_DRIVER
          value: "redis"
        - name: REDIS_SERVERS
          value: "rfs-redisfailover.default.svc.cluster.local:6379:0"
        - name: REDIS_SERVER
          value: "tcp://rfs-redisfailover.default.svc.cluster.local:26379?timeout=0.100"

        ### S3 Storage configuration
        - name: STORAGE_TYPE
          value: "local"
        volumeMounts:
        - mountPath: "/config"
          name: bookstack-temp
        - mountPath: "/app/www/storage/uploads/images"
          name: images
        - mountPath: "/app/www/storage/uploads/files"
          name: attachments
        readinessProbe:
         httpGet:
           path: /status
           port: 80
         initialDelaySeconds: 5
         timeoutSeconds: 1
         periodSeconds: 15
        # livenessProbe:
        #  httpGet:
        #    path: /login
        #    port: 80
        #  initialDelaySeconds: 15
        #  timeoutSeconds: 1
        #  periodSeconds: 15
      volumes:
        - name: bookstack-temp
          emptyDir:
            sizeLimit: 500Mi
        - name: images
          persistentVolumeClaim:
            claimName: uploads-nfs-pvc
        - name: attachments
          persistentVolumeClaim:
            claimName: attachments-nfs-pvc
