apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bookstack
  name: uploads-nfs
  labels:
    storage.k8s.io/name: uploads-nfs
    storage.k8s.io/created-by: alex-j-butler
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: bookstack
    name: uploads-nfs-pvc
  nfs:
    server: 10.1.200.230
    path: /volume1/docs-uploads/images
    readOnly: no
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: bookstack
  name: uploads-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: bookstack
  name: attachments-nfs
  labels:
    storage.k8s.io/name: attachments-nfs
    storage.k8s.io/created-by: alex-j-butler
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: bookstack
    name: attachments-nfs-pvc
  nfs:
    server: 10.1.200.230
    path: /volume1/docs-uploads/attachments
    readOnly: no
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: bookstack
  name: attachments-nfs-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi