---
apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
spec:
  type: LoadBalancer
  selector:
    app: bind9
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name: bind9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: ubuntu/bind9:edge
        env:
        ports:
        - containerPort: 53
        volumeMounts:
        - name: dns-configmap
          mountPath: /etc/bind/named.conf
          subPath: named.conf
      volumes:
      - name: dns-configmap
        configMap:
          name: dns-configmap