apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bookstack-secrets
  namespace: md-converter
spec:
  encryptedData:
    bookstack_token: AgC8/mbiXYwXp9Aax7zZu3LkB6uxDT3waDqCfZgvPcr4zKIMD1DVMMy5dcmz8AD9w2+2IChDE4QonpA7zCvM2eD47zPWfKt1KWCNZh9/T08oFbEAZVWl3X8Fv4OSr05CBwsbcN9buoYriJO9SQfzF4qg/0fZm5G6mbV5T20hzFpkT4fsVTE6kPHFzPQqItJQ/8za1pMqhH19jQkPZaU5GewdzWo6p6lisUH4xHdvE66h4CuJXiT6Z6WW0piDHbHQt8D3OF092qger5OTxkXmMhc4cfoArV58mkNW6UYYRF/zsjdWOulJnGK5KNpDlwYfQTKIDdhYHdFLfgHGiAa0+cnkzgG7r4N1m050GaRCE8u/I2c3ve/ERtLACkXq/rVbTMr+q3l864zG4CVopxP3Eku/M08qyFTaglN1cLIOxL2oq/CTv0HJRv4USorWP7dgRxLRHtKi3w/+3bJqqrlFMlMUzdQyXz34RheaY92OKMElIyPJkG2tshAadNFgIMOP7U+nPYrhvcXpbvbRmncR+mRm6iAoQTfG8StBvWLmrAyOoLr1+/JwbB1oVLuI5MUh/6hnaFleurmAU1llthR0f9Mr9sHzYcnAvfcHZtAIxU8RTq5/VYljXVeBYx2JF145pc4y4htBr/Vrbf0WBxSKwpz4bhdJHH7zUB0VO/DyWsmmFIWGqP4wWbl0rbuw/aONwogdEBtaHfbdt+5hBM4qo4CXHGcSh5BR1MXbkIQh5mPV5N80Wy9HebkMjdNQNpMuYUdr098bmbObfJ3Zr+3WOs3KPw==
    bookstack_url: AgBDYMdk8NPIN2l0nVHz9LV948cRKpmzrf6P3bJk+rB2k9DSG23+NAUgrrUGEHeQwCATCE4H/LQGMiQQJ7uI0XhMpluh60J2CR1gJlFB15k7OYtzxCtKl3/NYA0tESKg2O+x8RNdQN5Y2eual+IB5Ze5Yh9l3bHKtKaK5EIBRu8MjbnV94Lu2ATO0yI6vLt3gX9RjS3wPCf30n5ABxYZG32Lc3Ws/XxYAyXZM2fw2+iNc71Wv/91uDwNaTgUKaCXmzmybEzZSIFU6hdZGfxcHjZySY105fMKjQXxjLp1aKqBJ3a9KDKoBWYWxuVJRxSRh+1rJZod37wS6oOitq7w6b2madL5SuC/GZJONRMd4fQbiEb7gjCZ/uOSb1ckahFRLc4FboLUTrNAzqELDJc/KVSbLVNCKDMk1mRe3KVDPWdgvgrw9zifSgnuPiR0C+RZAU3x3A3PqNo4FxuxQDJhHnrDLBPFiJFlrZ7WFqr1AjnlJtvG3tm7xUUXCCLcStmcU7fZW/BICX27esLmbINqhcftCinwac3Lj5c/L/8tSEBAO+M5Qm/lM8YbE4ExgZmdlx7lRg9xEuw2+eugujB8PIl88n6OKhIeoIa6QfwnqBa42tVEKb/65nKp/9Odxs9rifMW/cbErFv/0RKpv6MM+IYFRaC16qbdoia0kBOPJML8KXnEfcsGCXZh+8PHZahYTkaHUDphOg3A5DIfX6Ruu/xfnMolJe1pMUxiG2PNYaA=
  template:
    metadata:
      creationTimestamp: null
      name: bookstack-secrets
      namespace: md-converter
    type: Opaque
status: {}

