apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-secrets
  namespace: md-converter
spec:
  encryptedData:
    access-key: AgB0ujWNOhNMFoEocyUzxtqCUEJ0IR/CJWSnHVJE2QWT3XEKIaBxZjwASdOTQ887k+Qj5QYj+ywrOfbUaf+TMJzlNh9mui54ghhJ4DMi3XLhiC19oZJi+v1A7mSbv4Y+T3mZRO7/HvW+/o3Wu7X+jDcNFWSiga/SGrko0W380RgIjdjDkGj+cQCKYORyNUMIZTFNHfJRRkVMlX72pp0TlNx4fFxPXpMzzSCURAqM1Nl4fM7clhLmC7nXpOEIhlRlN1c2pTeIZeGDP3mm6ZtYT+jnxZJOHXd5sjNzRmUF1BRnQqX4pYkHY4KJAeOXG4GzoX1M0Cb7jL6UG2tK2OeSgWiXPqT7rA8N84iJMIv2SBWSLKqvZW2L8TWLz6hwnxuxJSYQ0hadGwZVwAyChUgkjK5tTdqfOncxt5PqhfdO9eBpFXLmwcGmSRRryK/W6zx409yS7hqxxeNPHUSuRhwv/3fna3IU01bxRfJEX8jtt9OiiVqNkfJVqjMI75s3bnC9pXndXrm277iexjW+zlSsU9YKljqKVNhV0nKDuE6aI7Ye8dU6EkxpVcEiBBpGzaqIbNAubIK10ILsviIeI8FSAp1/lNfeccpgPV1OKLcDDDO+K86Toc+6Bv8Y82gPDj8JkPRMhQ6uTBwgUxi4oRt8qo00kzzNaL/lSu5q1gPiBOt3rC865RDyqCfZeH6LpU1JwpPwVY8sx2xYwAbV5LmJuEHBxU8WGg==
    secret-key: AgCqJv2ykVq2g5H2to+rl5H+570sYq6NhweW7+q0oNO0QMc1R36p+8UwtCnQRPVPdbR1MbcbjVHKQFsqZIuXkOnBiLdUsWFgjK4pbW688X0T36iLGLquvpY+tPDa2WbCU/Oa3sCYxfF66ISrO5JP0iG81iWoNpT0CgT7QPjRDuNgB5noG8KDK16xYI8g68WboXU1D4Rx55KeTjLdl+mjkgB1/mFDX9wr8IALDFPBYBx9Dghe2K2klkt3cX6U5ZUyHQU2D7fHou0zNX79xG9ObE7LEi0DFjsxGvqqSR9IIxFOzXDPq/qUZnPVQ8E/DcmUSoOHOieig7YFR8jQ04U1/i1YsdDHmMm6/br63FubYkGLgYs0v+AjXXhoAtva5WixcK9kGtx8t0AbH/WqljWxdY4Je8WEqoQSZ/VwQQNx6lc49K7ITtI+/+KeCUZvt+IEr9cIsO5OEd4iJlmQs5LK22ykWIWlfR0FnQyQS91LAFKYb3txmCtd2n75tDHsWFOeNf4glIcTWdlYeAqlm3xrBYCYa9kJWTrshrck6dYokhS42ooCtCGZa5vr3dezgrZaJAptCs0Zsfnv9pD/2dkv3ntMgN8yo9j2GuNCTP/0+dY2eu7Z6w0OOr35o47V1kf45WBtHW5lHmU+CxaKNUfZTn5NPQBzzQOYHnNLxbn1TMhfXzF0Ixal/4KQJ56APCPVakVJ5Se1I+2KJlB4O/3pOblk567Ouor9CE1wo2rthtsfciQ4jkUu1a4H
  template:
    metadata:
      creationTimestamp: null
      name: s3-secrets
      namespace: md-converter
    type: Opaque
status: {}
