apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: md-converter
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
      - name: web
        image: ghcr.io/alex-j-butler/markdown-converter-api/web:1.0.3
        ports:
        - containerPort: 8000
        env:
        - name: MDCONVERTER_BROKER_URL
          value: "amqp://guest@rabbitmq-svc.rabbitmq.svc.cluster.local"
        - name: MDCONVERTER_RESULT_BACKEND_URL
          value: "celery_amqp_backend.AMQPBackend://guest@rabbitmq-svc.rabbitmq.svc.cluster.local"
