apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  namespace: mysql-cluster
  name: mysqlcluster
spec:
  secretName: sql-pwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 3
  datadirVolumeClaimTemplate:
    storageClassName: "directpv-min-io"
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mycnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    max_allowed_packet=128M
    innodb_buffer_pool_size=1G
  podSpec:
    containers:
      - name: mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            mysql.oracle.com/cluster: mysqlcluster