apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  namespace: mysql-cluster
  name: mysqlcluster
spec:
  secretName: sql-pwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2
  datadirVolumeClaimTemplate:
    storageClassName: "storage-synology-iscsi"
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  backupProfiles:
  - name: daily
    dumpInstance:
      storage:
        persistentVolumeClaim:
          claimName: sql-backup-pvc
  backupSchedules:
  - name: daily-sql-schedule
    schedule: "0 0 * * *" # Daily, at midnight
    backupProfileName: daily # reference the desired backupProfiles's name 
    enabled: true # backup schedules can be temporarily disabled
  mycnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    max_allowed_packet=128M
  podSpec:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            mysql.oracle.com/cluster: mysqlcluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mysql-cluster
  name: sql-backup-pvc
  annotations:
    k8up.io/backup: "false"
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi