apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  namespace: mysql-cluster
  name: mysqlcluster
spec:
  secretName: sql-pwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2
  datadirVolumeClaimTemplate:
    storageClassName: "storage-synology-iscsi"
    accessModes: 
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  mycnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    max_allowed_packet=128M
  podSpec:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            mysql.oracle.com/cluster: mysqlcluster