apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- express-secrets.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: helpers-configmap
  files:
  - helpers-config.js
