apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: external
  name: external-ingress
  annotations:
    # custom max body size for file uploading like backing image uploading
    # nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - pwd.alex-j-butler.com
    secretName: pwd-external-tls
  - hosts:
    - homeassistant.alex-j-butler.com
    secretName: hassio-external-tls
  - hosts:
    - plex.alex-j-butler.com
    secretName: plex-external-tls
  rules:
  - host: pwd.alex-j-butler.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pwd-external-service
            port:
              number: 80
  - host: homeassistant.alex-j-butler.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hassio-external-service
            port:
              number: 80
  - host: plex.alex-j-butler.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: plex-external-service
            port:
              number: 80
      - pathType: Prefix
        path: "/sonarr"
        backend:
          service:
            name: sonarr-external-service
            port:
              number: 80
      - pathType: Prefix
        path: "/radarr"
        backend:
          service:
            name: radarr-external-service
            port:
              number: 80
      - pathType: Prefix
        path: "/bazarr"
        backend:
          service:
            name: bazarr-external-service
            port:
              number: 80
      - pathType: Prefix
        path: "/stats"
        backend:
          service:
            name: stats-external-service
            port:
              number: 80