apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
  namespace: budget
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
