apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: karaoke-media-nfs
  name: media-nfs
  labels:
    storage.k8s.io/name: karaoke-media-nfs
    storage.k8s.io/created-by: alex-j-butler
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: karaoke
    name: karaoke-media-nfs-pvc
  nfs:
    server: 10.1.200.230
    path: /volume1/Media/Karaoke
    readOnly: no