apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karaoke-config-pvc
  namespace: karaoke
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: karaoke-media-nfs-pvc
  namespace: karaoke
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi