apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-pvc
  namespace: media
spec:
  storageClassName: "storage-synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi